"""Assemble the per-backend driver briefs from the shared core + a backend stub.

One source of truth (`standard_prompt.md`) -> consistent, method-neutral briefs.
Edit the core or a stub, then re-run this to regenerate the *_DRIVER_BRIEF.md files.
The generated briefs are self-contained (paste the BEGIN..END block into a fresh
session); only the "How to drive" stub differs between tracks.
"""
from pathlib import Path

HERE = Path(__file__).resolve().parent      # benchmarks/m3_ai_assembly/prompts
BENCH = HERE.parent                          # benchmarks/m3_ai_assembly

core = (HERE / "standard_prompt.md").read_text(encoding="utf-8")
core_body = core[core.index("## Task"):]     # drop the core file's title + editor note
top, bottom = core_body.split("<!--BACKEND_STUB-->", 1)

HEADER = """# {title}

> **HOW TO USE:** Paste everything between the `=== BEGIN ===` / `=== END ===`
> markers into a **fresh agent session** ({host}), started in a **neutral working
> folder** — no CADCLAW checkout, no `AGENTS.md`, no project memory — so no reference
> solution, build-order guidance, or answer-key hint can leak in. This brief + the kit
> are the *only* design inputs. After the run, hand the exported STEP to the grader
> session (`grade_native_step.py`).
>
> GENERATED from `prompts/standard_prompt.md` + `prompts/{stub}` by
> `prompts/build_briefs.py`. **Do not edit this file by hand** — edit the core or the
> stub and re-run the assembler.

---

`=== BEGIN ===`

You are the **{role}** in an AI-CAD assembly benchmark. {intro} You are being timed
and graded; work only from this brief + the kit.

"""

FOOTER = """

`=== END ===`

---

*Grader-side (not part of the driver prompt):* grade the exported STEP with
`benchmarks/m3_ai_assembly/scripts/grade_native_step.py` + `score_report.py` — the
same gates as every track. This is a **blind** track: compare blind-vs-blind across
tracks; the resolver-built reference (~15/100 full-stack) is the informed ceiling,
not a competitor.
"""

TRACKS = {
    "FUSION_DRIVER_BRIEF.md": dict(
        title="Fusion Driver Brief — CADCLAW assembly benchmark (generated)",
        host="Claude Code with the Autodesk Fusion MCP",
        role="Claude-Fusion driver",
        intro="Build the machine in Autodesk Fusion (via the Fusion MCP), then export a single STEP.",
        stub="stub_fusion.md",
    ),
    "CADQUERY_DRIVER_BRIEF.md": dict(
        title="CadQuery Driver Brief — CADCLAW assembly benchmark (generated)",
        host="Claude Code, or GPT / Codex — the model under test",
        role="CadQuery driver",
        intro="Build the machine in CadQuery (Python) from the kit, then export a single STEP.",
        stub="stub_cadquery.md",
    ),
}

for fname, t in TRACKS.items():
    stub = (HERE / t["stub"]).read_text(encoding="utf-8")
    header = HEADER.format(title=t["title"], host=t["host"], role=t["role"],
                           intro=t["intro"], stub=t["stub"])
    brief = header + top.strip() + "\n\n" + stub.strip() + "\n\n" + bottom.strip() + FOOTER
    (BENCH / fname).write_text(brief, encoding="utf-8")
    print(f"wrote {fname} ({len(brief)} chars)")
